WIDTH_ADDRESS = 8
WIDTH_INSTRUCTION = 24
WIDTH_COMMENT = 100

DELIMITER_SPLIT_COMMENT = "..."
PRE_DOTS = DELIMITER_SPLIT_COMMENT + " "
POST_DOTS = " " + DELIMITER_SPLIT_COMMENT
DELIMITER_COMMENT = ";"
DELIMITER_LEFT = DELIMITER_COMMENT + " "
DELIMITER_RIGHT = " " + DELIMITER_COMMENT

COL_INDEX_ADDRESS = 0
COL_INDEX_INSTRUCTION = 1
COL_INDEX_COMMENT= 2